# Generated by Django 2.0.2 on 2018-05-11 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marudy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maruda',
            name='hunter',
        ),
        migrations.AddField(
            model_name='maruda',
            name='like_control',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
