# Generated by Django 2.0.2 on 2018-05-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marudy', '0002_auto_20180511_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarudaVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='maruda',
            name='like_control',
        ),
        migrations.AddField(
            model_name='marudavoting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted', to='marudy.Maruda'),
        ),
        migrations.AddField(
            model_name='marudavoting',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
