# Generated by Django 2.0.2 on 2018-05-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marudy', '0003_auto_20180511_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marudavoting',
            old_name='user',
            new_name='maruda',
        ),
    ]
